### ISSUE TITLE
Update for Swift 5 and add swift version to podspec

### ISSUE THREAD

**Issue by undsoft** [phimage/CustomSegue#7]
Hey,

With xcode 10 out and since podspec doesn't specify swift version, swift 5 is being used by default which leads to compilation problems.

I can manually change pod's swift version, but it would have been better to either:
* have support for swift 5
* and/or have swift version specified in podspec.

Thanks

**Comment by phimage** [comment]
Updated to swift 5.0
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  CustomSegue (4.0.0) successfully published
 📅  April 9th, 15:59
 🌎  https://cocoapods.org/pods/CustomSegue
 👍  Tell your friends!
--------------------------------------------------------------------------------


in podspec I add nothing because current cocoapods-1.6.1 failed
```
The following validation failed:
- Warnings: Unrecognized `swift_version` key.
```
